"""Adding some collumns

Revision ID: 6766e8a522d6
Revises: bf4f11a6bc84
Create Date: 2023-11-10 15:16:37.747756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6766e8a522d6'
down_revision = 'bf4f11a6bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_done', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('year_or_grade', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('subjects', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('score', sa.String(length=4), nullable=True))
        batch_op.drop_column('Term')
        batch_op.drop_column('Subject')
        batch_op.drop_column('Score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Score', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('Subject', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('Term', sa.INTEGER(), nullable=False))
        batch_op.drop_column('score')
        batch_op.drop_column('subjects')
        batch_op.drop_column('year_or_grade')
        batch_op.drop_column('year_done')
        batch_op.drop_column('term')

    # ### end Alembic commands ###
