"""Created Exams table

Revision ID: bf4f11a6bc84
Revises: 7d1c802541e0
Create Date: 2023-11-10 14:54:18.595185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4f11a6bc84'
down_revision = '7d1c802541e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('Subject', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('Score', sa.String(length=4), nullable=True))
        batch_op.drop_column('English')
        batch_op.drop_column('School')
        batch_op.drop_column('Math')
        batch_op.drop_column('Comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Comment', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Math', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('School', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('English', sa.INTEGER(), nullable=False))
        batch_op.drop_column('Score')
        batch_op.drop_column('Subject')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
